# Conexión a Postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/zentinel_db
spring.datasource.username=postgres
spring.datasource.password=maomaosar1

# Estrategia de JPA
# Usamos 'validate' porque tú ya creaste las tablas manualmente con el script SQL
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect